version: '3'

services:
  
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "7000:6645"
    networks:
      - "flamingo-network"
  
  customer-service:
    build:
      context: ./customer-service 
      args:
        POSTGRES_PASSWORD: Abc.12345
        POSTGRES_DB: customer_db   
    container_name: customer-service
    networks: 
      - "flamingo-network"

  customer-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Abc.12345
      POSTGRES_DB: customer_db
    container_name: customer-db
    networks: 
      - "flamingo-network"
  
  email-service:
    build: ./email-service
    container_name: email-service
    networks: 
      - "flamingo-network"

  log-service:
    build: ./log-service
    container_name: log-service
    networks: 
      - "flamingo-network"

  order-service:
    image: mongo
    build: 
      context: ./order-service
    container_name: order-service
    networks: 
      - "flamingo-network"

  message-broker:
    image: rabbitmq
    environment: 
      HOSTNAME: message-broker
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_VHOST: /
    container_name: message-broker
    networks: 
      - "flamingo-network"

networks: 
  flamingo-network:
    driver: bridge